### ISSUE TITLE
Testing snippet does not work

### ISSUE THREAD

**Issue by belkka** [fabiocaccamo/django-extra-settings#4]
**Python version** 3.7.7

**Django version** -

**Package version** git repo, commit 33604ef38ca8a99df3a2c872ddea03d0f2d210a2

**Current behavior (bug description)**
Running [testing snippet](https://github.com/fabiocaccamo/django-extra-settings/blob/33604ef/README.md#testing) line by line from the README results in failing tests:

```bash
$ python setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
creating django_extra_settings.egg-info
writing django_extra_settings.egg-info/PKG-INFO
writing dependency_links to django_extra_settings.egg-info/dependency_links.txt
writing requirements to django_extra_settings.egg-info/requires.txt
writing top-level names to django_extra_settings.egg-info/top_level.txt
writing manifest file 'django_extra_settings.egg-info/SOURCES.txt'
reading manifest file 'django_extra_settings.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found under directory '*'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '.DS_Store' found under directory '*'
writing manifest file 'django_extra_settings.egg-info/SOURCES.txt'
running build_ext
runtests (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: runtests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: runtests
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/ulianich/projects/testing_django_extra_settings/src/runtests.py", line 6, in <module>
    import django
ModuleNotFoundError: No module named 'django'


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
```

Note: I omit a `--no-site-packages` in the first command, because it's an invalid option for virtualenv. See related [PR](https://github.com/fabiocaccamo/django-extra-settings/pull/3)

**Expected behavior**
It's essential to expect that running the sequence of commands in the snippet results in successful test run. Looks like there is a missing "install requirements" step. `pip install -r requirements.txt` does not solves the issue, because there is only "six" package [in requirements](https://github.com/fabiocaccamo/django-extra-settings/blob/33604ef38ca8a99df3a2c872ddea03d0f2d210a2/requirements.txt#L1), but no django.

**Comment by belkka** [comment]
Also, note: another command suggested to run tests is
```
python manage.py test --settings "tests.settings"
```

**Comment by fabiocaccamo** [comment]
Thank you @belkka I will test and fix it.

**Comment by belkka** [comment]
Thanks for update!
